//! # cactus-sys
//!
//! Low-level FFI bindings for [Cactus](https://github.com/cactus-compute/cactus),
//! a cross-platform, energy-efficient AI inference engine for mobile devices.
//!
//! This crate provides raw, unsafe bindings generated by bindgen. For a safe,
//! idiomatic Rust API, use the `cactus` crate instead.
//!
//! ## Features
//!
//! - `metal` (default) - Enable Metal GPU acceleration on macOS/iOS
//! - `vulkan` - Enable Vulkan GPU acceleration on Android
//!
//! ## Example
//!
//! ```rust,ignore
//! use cactus_sys::*;
//! use std::ffi::CString;
//! use std::ptr;
//!
//! unsafe {
//!     let path = CString::new("/path/to/model.gguf").unwrap();
//!     let model = cactus_init(path.as_ptr(), 2048, ptr::null());
//!
//!     if !model.is_null() {
//!         // Use model...
//!         cactus_destroy(model);
//!     }
//! }
//! ```

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

// Include generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bindings_exist() {
        // This test just verifies the bindings compile
        // Actual functionality requires a model file
        unsafe {
            let error = cactus_get_last_error();
            // Should return null or empty string when no error
            assert!(error.is_null() || *error == 0);
        }
    }
}
